version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: escashop_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./src/database/complete-migration.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./src/database/migrations/create_daily_queue_history_tables.sql:/docker-entrypoint-initdb.d/02-daily-history.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d escashop_test"]
      interval: 10s
      timeout: 5s
      retries: 5
    tmpfs:
      - /tmp
      - /var/run/postgresql

volumes:
  postgres_test_data:
